const mangas = [
  {
    id: 1,
    titulo: "One Piece",
    autor: "Eiichiro Oda",
    imagem: "https://sm.ign.com/t/ign_br/tv/o/one-piece-/one-piece-2_1xby.1200.jpg",
    volumes: 111,
    genero: "Shōnen, Aventura",
    demografico: "Shōnen",
    iniciado: 1997,
    circulacao_mundial: 516_000_000,
    sinopse: "As aventuras de Monkey D. Luffy e sua tripulação em busca do tesouro One Piece. É o mangá mais vendido da história." ,
    requisitos: "Gosta de histórias longas com muita ação, mundo vasto e comédia."
  },
  {
    id: 2,
    titulo: "Dragon Ball",
    autor: "Akira Toriyama",
    imagem: "https://mediaproxy.tvtropes.org/width/1200/https://static.tvtropes.org/pmwiki/pub/images/dbzbig.png",
    volumes: 42,
    genero: "Shōnen, Ação, Artes Marciais",
    demografico: "Shōnen",
    iniciado: 1984,
    circulacao_mundial: 260_000_000,
    sinopse: "Siga Goku desde sua infância até seus confrontos épicos em prol da Terra.",
    requisitos: "Ideal para fãs de lutas intensas e evolução de personagem."
  },
  {
    id: 3,
    titulo: "Naruto",
    autor: "Masashi Kishimoto",
    imagem: "https://blogbeautifuldreams.wordpress.com/wp-content/uploads/2013/07/naruto.jpg?w=1130",
    volumes: 72,
    genero: "Shōnen, Ação, Ninja",
    demografico: "Shōnen",
    iniciado: 1999,
    circulacao_mundial: 250_000_000,
    sinopse: "Naruto Uzumaki, um ninja solitário, busca reconhecimento e deseja se tornar Hokage.",
    requisitos: "Gosta de histórias com superação, amizades e ninjas."
  },
  {
    id: 4,
    titulo: "Demon Slayer: Kimetsu no Yaiba",
    autor: "Koyoharu Gotōge",
    imagem: "https://image.api.playstation.com/vulcan/ap/rnd/202106/1704/JzL1NLQvok7Pghe9W5PP2XNV.png",
    volumes: 23,
    genero: "Shōnen, Fantasia, Ação",
    demografico: "Shōnen",
    iniciado: 2016,
    circulacao_mundial: 220_000_000,
    sinopse: "Tanjiro se torna caçador de demônios para salvar sua irmã Muzan e vingar sua família.",
    requisitos: "Se gosta de fantasia sombria, emoções fortes e arte marcante."
  },
  {
    id: 5,
    titulo: "Attack on Titan",
    autor: "Hajime Isayama",
    imagem: "https://upload.wikimedia.org/wikipedia/pt/e/e7/SnK_Volume1.png",
    volumes: 34,
    genero: "Shōnen, Fantasia sombria, Mistério",
    demografico: "Shōnen",
    iniciado: 2009,
    circulacao_mundial: 140_000_000,
    sinopse: "Humanidade vive atrás de muros para se proteger de gigantes devoradores. Eren luta para desvendar esse massacre.",
    requisitos: "Recomendado para quem busca suspense, reviravoltas e temas adultos."
  },
  {
    id: 6,
    titulo: "Slam Dunk",
    autor: "Takehiko Inoue",
    imagem: "https://i0.wp.com/halcyonrealms.com/blogpics/slamdunknew20.jpg?resize=500%2C780&ssl=1",
    volumes: 31,
    genero: "Esportes, Comédia, Shōnen",
    demografico: "Shōnen",
    iniciado: 1990,
    circulacao_mundial: 185_000_000,
    sinopse: "Hanamichi Sakuragi entra no time de basquete para conquistar uma garota, mas acaba descobrindo sua paixão pelo esporte.",
    requisitos: "Perfeito para fãs de basquete, comédia e desenvolvimento de personagem."
  },
  {
    id: 7,
    titulo: "Berserk",
    autor: "Kentaro Miura",
    imagem: "https://upload.wikimedia.org/wikipedia/pt/thumb/4/45/Berserk_vol01.jpg/250px-Berserk_vol01.jpg",
    volumes: 41,
    genero: "Seinen, Fantasia sombria, Horror",
    demografico: "Seinen",
    iniciado: 1989,
    circulacao_mundial: 60_000_000,
    sinopse: "Guts, o Espadachim Negro, luta contra demônios em um mundo medieval sombrio. Uma obra-prima do mangá seinen com arte excepcional.",
    requisitos: "Para leitores maduros que apreciam narrativas complexas, violência gráfica e temas psicológicos profundos."
  },
  {
    id: 8,
    titulo: "Fruits Basket",
    autor: "Natsuki Takaya",
    imagem: "https://gqcanimes.com.br/wp-content/uploads/2021/03/Fruits-Basket-The-Final-GQCA.jpg",
    volumes: 23,
    genero: "Shōjo, Romance, Drama",
    demografico: "Shōjo",
    iniciado: 1998,
    circulacao_mundial: 30_000_000,
    sinopse: "Tohru Honda descobre que a família Soma está amaldiçoada a se transformar em animais do zodíaco chinês quando abraçados por alguém do sexo oposto.",
    requisitos: "Ideal para quem busca romance tocante, desenvolvimento emocional e temas de aceitação e cura."
  },
  {
    id: 9,
    titulo: "Nana",
    autor: "Ai Yazawa",
    imagem: "https://m.media-amazon.com/images/I/61RckExtAuL._UF1000,1000_QL80_.jpg",
    volumes: 21,
    genero: "Josei, Romance, Drama",
    demografico: "Josei",
    iniciado: 2000,
    circulacao_mundial: 50_000_000,
    sinopse: "Duas jovens mulheres chamadas Nana se conhecem em um trem para Tóquio e suas vidas se entrelaçam de forma complexa.",
    requisitos: "Perfeito para adultos jovens interessados em relacionamentos complexos, música e drama realista."
  },
  {
    id: 10,
    titulo: "Horimiya",
    autor: "Hero (história) e Daisuke Hagiwara (arte)",
    imagem: "https://m.media-amazon.com/images/I/81CPg26GQ2L._UF1000,1000_QL80_.jpg",
    volumes: 16,
    genero: "Romance, Slice of Life, Comédia",
    demografico: "Shōnen",
    iniciado: 2011,
    circulacao_mundial: 8_000_000,
    sinopse: "Kyouko Hori e Izumi Miyamura descobrem os lados ocultos um do outro e desenvolvem um relacionamento inesperado.",
    requisitos: "Ideal para quem gosta de romance realista, desenvolvimento de personagem e situações do dia a dia."
  },
  {
    id: 11,
    titulo: "Uzumaki",
    autor: "Junji Ito",
    imagem: "https://m.media-amazon.com/images/I/91sX45cfZWL._UF1000,1000_QL80_.jpg",
    volumes: 3,
    genero: "Horror, Sobrenatural, Psicológico",
    demografico: "Seinen",
    iniciado: 1998,
    circulacao_mundial: 2_000_000,
    sinopse: "A cidade de Kurouzu-cho é assombrada por espirais que causam eventos sobrenaturais e aterrorizantes.",
    requisitos: "Recomendado para fãs de horror psicológico, arte única e narrativas perturbadoras."
  },
  {
    id: 12,
    titulo: "Yotsuba&!",
    autor: "Kiyohiko Azuma",
    imagem: "https://m.media-amazon.com/images/I/91+0p+6pOJL.jpg",
    volumes: 15,
    genero: "Slice of Life, Comédia, Infantil",
    demografico: "Seinen",
    iniciado: 2003,
    circulacao_mundial: 15_000_000,
    sinopse: "As aventuras diárias de Yotsuba, uma garotinha energética e curiosa, explorando o mundo ao seu redor.",
    requisitos: "Perfeito para quem busca histórias reconfortantes, humor inocente e uma perspectiva otimista da vida."
  },
  {
    id: 13,
    titulo: "Paradise Kiss",
    autor: "Ai Yazawa",
    imagem: "https://media.fstatic.com/Y3woEjQdMA-hvgvcld9YbrRsetM=/fit-in/640x480/smart/filters:format(webp)/media/movies/covers/2011/04/70ae7e70f062d3a7fe563c100bc67ed1.jpg",
    volumes: 5,
    genero: "Josei, Romance, Moda",
    demografico: "Josei",
    iniciado: 1999,
    circulacao_mundial: 3_000_000,
    sinopse: "Yukari, uma estudante do ensino médio, é descoberta por estudantes de moda e se envolve no mundo da alta costura e do amor.",
    requisitos: "Ideal para quem se interessa por moda, romance maduro e arte estilizada."
  }
];

export default mangas;